name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set version
      id: set_timestamp
      run: echo "::set-output name=timestamp::$(date +%s)"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anhnguyen4198/react-app:${{ steps.set_timestamp.outputs.timestamp }}

    - name: Log in to Docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker hub
      run: docker push anhnguyen4198/react-app:${{ steps.set_timestamp.outputs.timestamp }}
